---
title: 'CAGE: Check Feature Selection'
author: "John Thompson"
date: "2023-03-29"
output: 
    prettydoc::html_pretty:
      theme: cayman
---

```{r setup, include=FALSE}
# --- theme cayman requires  R package prettydoc
library(tidyverse)
library(glue)
library(fs)

# --- cache results from features.R
cache <- "C:/Projects/RCourse/Masterclass/CAGE/data/cache"
loss <- readRDS(path(cache, "feature_loss.rds")) 

# --- chunk options
knitr::opts_chunk$set(echo = TRUE, 
                      fig.align = "center",
                      message=FALSE)
```

## Background

Feature selection results from features.R

## Warning Messages

```{r}
readLines(path(cache, "features_log.txt"))
```

## Method 1: Most Predictive Probes

```{r}
loss$probeUniDF %>%
  print() %>%
  arrange(loss) %>%
  print()
```

```{r}
print(loss$probeSelectedDF)
```


## Method 2: Most Predictive Unscaled PCs

```{r}
loss$vpcaUniDF %>%
  print() %>%
  arrange(loss) %>%
  print()

loss$vpcaSelectedDF %>%
  print()
```

```{r}
loss$vpcaOrderedDF %>%
  print()
```

## Method 3: First Unscaled PCs

```{r}
loss$vpcaOrderedDF %>%
  print()
```

## Method 4: Most Predictive Scaled PCs

```{r}
loss$cpcaUniDF %>%
  print() %>%
  arrange(loss) %>%
  print()

loss$cpcaSelectedDF %>%
  print()
```

## Method 5: First Scaled PCs

```{r}
loss$cpcaOrderedDF %>%
  print()
```

